# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -o bin/kubectl-localmesh main.go

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run Linters
    cmds:
      - yamllint -c .yamllint.yaml .
      - golangci-lint run

  format:
    desc: Format code
    cmds:
      - gofmt -w .
